### ISSUE TITLE
"There was an error when handling the request" in C1W1 FasrAPI

### ISSUE THREAD

**Issue by iamyufan** [https-deeplearning-ai/machine-learning-engineering-for-production-public#100]
I am trying to run server.ipynb on my MacBook with M2 chip. The server is able to be running on http://localhost:8000. But the following error always showed up when I tried the predict endpoint by either uploading an image in the browser or in the client.ipynb.

![image](https://github.com/https-deeplearning-ai/machine-learning-engineering-for-production-public/assets/70952634/ee249fb4-3019-4b21-a513-b25b96963961)

**Comment by Michael-YaoYiWei** [comment]
I encounter the same issue, please any one could help here, thankt

**Comment by cfav-dev** [comment]
Hi Yufan and Michael. Sorry for the late reply. Next time, you can post or search for similar topics in our community. There might be mentors/learners there who have the same setup and can help you. If you haven't joined yet, you can find instructions in Week 1 of your classroom. Thank you!
