### ISSUE TITLE
conlist() Error

### ISSUE THREAD

**Issue by sreiswig** [https-deeplearning-ai/machine-learning-engineering-for-production-public#103]
When running week2-ungraded-labs/C4_W2_Lab_1_FastAPI_Docker/with-batch

the call to conlist() causes an error.
This error is due to using the syntax for Pydantic 1.10
When following the Readme instructions the latest version of Pydantic 2.3 is used

This breaks the code as conlist now expects min_length and max_length instead of min_items and max_items as keyword arguments

**Comment by Ed-Cheng** [comment]
Thanks! I also faced the problem. Changing min_items and max_items to min_length and max_length in the main.py file DID fix the issue!

**Comment by Yadukrishnan1** [comment]
Checking in to see if this got resolved.

**Comment by cfav-dev** [comment]
Thanks, Sam!
