### ISSUE TITLE
Course 4 : error collecting test_clf.py

### ISSUE THREAD

**Issue by chris-caballero** [https-deeplearning-ai/machine-learning-engineering-for-production-public#104]
There seems to be an error with the scikit-learn version interaction with pickle load. 

This was encountered when trying to apply the unit test 'test_clf.py' on commit. sklearn is downloaded with requirements.txt, this may be the problem, a specific version would likely fix this issue.

**Comment by JohnBounty** [comment]
Greetings!
@chris-caballero, you are absolutely right. To fix the problem one can change `scikit-learn` to `scikit-learn==1.2.2` in the `requirements.txt`. 

Note, that after that there will most likely be an error with `conlist()` in `main.py`. It can be solved either by changing `min_items` and `max_items` parameters to `min_length` and `max_length` respectively, or by removing those altogether.

**Comment by mmitrou** [comment]
Hi!
This change of scikit-learn version created issue with cython3 compatibility. The suggestion is to limit python to 3.10 (and in turn update `.github/workflows/course4-week3-lab.yml` so that:
`on:
  # Triggers the workflow on push request events only when there are changes in the desired path
  push:
    paths:
      - 'course4/week3-ungraded-labs/C4_W3_Lab_4_Github_Actions/**'
      - '.github/workflows/**'`
      (or trigger the pipeline manually)

**Comment by cfav-dev** [comment]
Hi everyone! Thank you for reporting, and sorry for the delay! The problematic files are now updated, so the learners shouldn't run into the issues anymore.
