### ISSUE TITLE
Mac M1 Users - Link to solution

### ISSUE THREAD

**Issue by andres-zartab** [https-deeplearning-ai/machine-learning-engineering-for-production-public#24]
This resource contains information on how to install TF locally for Mac M1 users: https://github.com/apple/tensorflow_macos/issues/153

**Comment by mygithubid1** [comment]
It would be good to mention Mac M1 support for tensorflow in the resources section.

Here's a post from a student looking for this information:
https://community.deeplearning.ai/t/how-to-serve-the-model-using-tensorflow-serving-docker-image-on-m1-arm64-architecture/102169

**Comment by andres-zartab** [comment]
There is an additional file explaining how to get this working since Sept 2022 (this [one](https://github.com/https-deeplearning-ai/machine-learning-engineering-for-production-public/blob/main/course1/week1-ungraded-lab/mac_m1.md)). @cfav-dev do you think this is enough or should we also put an additional note in the resources section?

**Comment by cfav-dev** [comment]
@andres-zartab . If the additional file is on the repo and the README mentions it, I think putting a copy in the Resources is a nice-to-have but not critical. When a learner asks about the steps, we can point to the link in the README. If it's not mentioned, however, then we should add a note about it, or place it in the Resources section so mentors can refer to it. I think it's better to link to it in the notebook though. Thanks.

**Comment by andres-zartab** [comment]
In this case there is no notebook, or rather they need to go to the mkdown in order to run the notebook locally but I agree with what you said. I think it is highlighted enough so that we don't need to add this to the resources right away. Will close for now, thanks!
