### ISSUE TITLE
docker container for course1 lab has empty /work path. no files there

### ISSUE THREAD

**Issue by mas-dse-aaalam** [https-deeplearning-ai/machine-learning-engineering-for-production-public#37]

**Comment by andres-zartab** [comment]
Hi @mas-dse-aaalam, As mentioned in the [pinned thread](https://www.coursera.org/learn/machine-learning-data-lifecycle-in-production/discussions/weeks/1/threads/qlCtYLHQEeuS9wo8jdZF7Q), our learner support and community-building activities have moved to Discourse. Please repost this there to get support from the course mentors and also your fellow learners. They will be happy to help you! [You can join it through this link](http://bit.ly/mlep-discourse). If you’re already a part of Discourse through the other DeepLearning.AI specializations (e.g. Deep Learning), then you can simply [log-in to your Discourse account](https://discourse.deeplearning.ai/login) and choose the category before posting. Hope to see you there!
