### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.1

### ISSUE THREAD

**Issue by jkwening** [https-deeplearning-ai/machine-learning-engineering-for-production-public#44]
Issue with the requirements.txt file. Pip is throwing an error for installing the tensorflow version specified in the c1w1-ugl.

`ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.1 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0)
ERROR: No matching distribution found for tensorflow==2.3.1`

Can someone check to confirm that 2.3.1 is correct version; it looks like it's no longer supported via pip. I'm using venv to install virtual env on Windows 10 machine.

I was able to install tensorflow without a problem via `pip install tensorflow`. Then deleted the tensorflow line from requirements file and installed the remaining modules.

**Comment by andres-zartab** [comment]
Hi @jkwening, thanks for reporting! Will look into it asap

**Comment by andres-zartab** [comment]
@jkwening where you able to run the lab with the updated dependencies? Will close for now but if you are facing any trouble let me know

**Comment by jkwening** [comment]
Yeah, I didn't have any problems running the lab after updating tensorflow
to the current version. I then removed it from the requirements file and
ran the rest of the dependencies specified in the file.
