### ISSUE TITLE
mlepc4w2-ugl Docker repo does not exist

### ISSUE THREAD

**Issue by ecorro** [https-deeplearning-ai/machine-learning-engineering-for-production-public#55]
This is used by the C4_W2_Lab_3_Latency_Test_Compose lab. When running the "docker-compose up" command, I get the error 

`"Error response from daemon: pull access denied for mlepc4w2-ugl, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"`

and if I go to Docker Hub, the repo actually is not there.

Can you please advise?

**Comment by andres-zartab** [comment]
As mentioned in the beginning of the lab
![Screen Shot 2022-02-27 at 1 26 24 PM](https://user-images.githubusercontent.com/22200558/155894879-60f18e23-f38e-4896-962a-9ca740ef3a22.png)
These images should have been built in a previous lab. They are not available in the hub.
