### ISSUE TITLE
Jupyter lab instruction for docker 

### ISSUE THREAD

**Issue by sbyasin** [https-deeplearning-ai/machine-learning-engineering-for-production-public#57]
In the docker [method instruction](https://github.com/https-deeplearning-ai/machine-learning-engineering-for-production-public/blob/main/course1/week1-ungraded-lab/README.md), it is suggested to use `http://localhost:8888/` to open the notebook. Instead `http://localhost:8888/lab` could be used for consistency between two methods.

**Comment by andres-zartab** [comment]
Nice suggestion! This will be implemented shortly, thanks!
