### ISSUE TITLE
Running docker image container in the background or detached mode

### ISSUE THREAD

**Issue by ankur-rana99** [https-deeplearning-ai/machine-learning-engineering-for-production-public#58]
The problem 
When i run command from wsl- terminal 
docker run --rm -p 80:80 mlepc4w2-ugl:no-batch
it basically run and stop taking cURL commands , so need to open some other terminal command window or CMD .
Solution 
to run specified cURL commands directly from wsl (terminal) , we should run docker image container in the background or detached mode 
you can use the docker run command followed by the -d flag (or detached flag) and followed by the name of the docker image
what worked for me 
docker run -d -p 80:80 mlepc4w2-ugl:no-batch

**Comment by andres-zartab** [comment]
Thanks for the suggestion, we would prefer to abstain from introducing extra concepts such as running containers in detach mode but a note about needing a second terminal has been added.
