### ISSUE TITLE
Need protobuf in requirements.txt to run this lab in the conda env

### ISSUE THREAD

**Issue by venkatacrc** [https-deeplearning-ai/machine-learning-engineering-for-production-public#59]
You need to add the following line in the requirements.txt file to successfully run this lab in Conda virtual env.

protobuf ~=3.19.0

**Comment by andres-zartab** [comment]
Hi @venkatacrc, which one of the labs (course and week) are you referring to?

**Comment by Nnamaka** [comment]
You might also consider `protobuf~=3.20.0` It worked for me. I'm Referring to cousrs1 week1

**Comment by aalvarezg-axpe** [comment]
Agree. Protobuf 3.20.x is required for course1 of week1

**Comment by SachinMishra-ux** [comment]
Right I tried with protobuf ~=3.19.0, and it worked.
