### ISSUE TITLE
Filepaths are 72% of the max windows filepath length

### ISSUE THREAD

**Issue by cejdan** [https-deeplearning-ai/machine-learning-engineering-for-production-public#60]
I ran into a issue cloning the repository on my Windows machine due to the very lengthy filepaths in the repository. The longest filepath in the repository is:
`machine-learning-engineering-for-production-public/course4/week2-ungraded-labs/C4_W2_Lab_2_Intro_to_Kubernetes/saved_model_half_plus_two_cpu/00000123/variables/variables.data-00000-of-00001` which is a whopping 189 characters. Sadly, the Windows OS MAX_PATH is still only 260 characters. This leaves users only 71 characters of filepath remaining, which in my case was not enough to store the repository where I wanted to on my system. I can solve the issue by cloning the repo near my root C:/ then changing the repository name to something shorter, but shorter paths within the repository would be preferred.

**Comment by havryliuk** [comment]
You can use the following git config command to allow long paths:

`git config --system core.longpaths true`
