### ISSUE TITLE
tensorflow packages in m1 mac

### ISSUE THREAD

**Issue by Yohnjparra** [https-deeplearning-ai/machine-learning-engineering-for-production-public#71]
ERROR: Could not find a version that satisfies the requirement tensorflow-macos (from versions: none)
ERROR: No matching distribution found for tensorflow-macos

**Comment by andres-zartab** [comment]
Can you provide additional info about your setup? What Python version were you using? After some research I found that this error is common in versions other than Python 3.8 but that is the one the lab tells to use. Let me know
