### ISSUE TITLE
Unable to clone repo

### ISSUE THREAD

**Issue by abdellah19jan** [https-deeplearning-ai/machine-learning-engineering-for-production-public#77]
Hello,

I can not clone the repo, see attachment for print screen of the error message.

Regards.

![Capture](https://user-images.githubusercontent.com/54366282/210208646-885c5a93-423d-4dd0-bfd6-a9be3c255408.PNG)

**Comment by Isaakkamau** [comment]
Hello, I am quite late but try using `git config --global http.sslVerify false` if you still got the issue

**Comment by andres-zartab** [comment]
Hi @abdellah19jan, were you able to solve this issue?
