### ISSUE TITLE
 Building wheel for opencv-python-headless error

### ISSUE THREAD

**Issue by dzzzzdy** [https-deeplearning-ai/machine-learning-engineering-for-production-public#81]
Hi, I got this error and can't find a solution when I installed the required packages.
Mac Pro intel
ERROR: Failed building wheel for opencv-python
ERROR: Could not build wheels for opencv-python, which is required to install pyproject.toml-based projects

**Comment by Isaakkamau** [comment]
@dzzzzdy try `pip install --upgrade pip setuptools wheel` then `pip install opencv-python`

**Comment by Isaakkamau** [comment]
@dzzzzdy try `pip install --upgrade pip setuptools wheel` then `pip install opencv-python` if not try the other solutions stated here at [Stackoverflow](https://stackoverflow.com/questions/63732353/error-could-not-build-wheels-for-opencv-python-which-use-pep-517-and-cannot-be)

**Comment by andres-zartab** [comment]
Hi @dzzzzdy were you able to solve this?

btw, thanks for helping out learners @Isaakkamau 😄

**Comment by dzzzzdy** [comment]
> @dzzzzdy try `pip install --upgrade pip setuptools wheel` then `pip install opencv-python` if not try the other solutions stated here at [Stackoverflow](https://stackoverflow.com/questions/63732353/error-could-not-build-wheels-for-opencv-python-which-use-pep-517-and-cannot-be)

Thanks for your help. I can install it on my laptop, even though there is still an import error. But I don't know why it doesn't work in the virtual environment. I appreciate your help

**Comment by andres-zartab** [comment]
@dzzzzdy are you using python 3.8 within the virtualenv? If the error keeps happening after upgrading setuptools and wheel I would recommend trying out the Docker method. Also consider joining our [community](https://community.deeplearning.ai/) where our mentors and team will help you. You can also find more information on our community in this Reading Item within [Coursera](https://www.coursera.org/learn/introduction-tensorflow/ungradedLti/3L0GK/important-have-questions-issues-or-ideas-join-our-community).

**Comment by dzzzzdy** [comment]
> @dzzzzdy are you using python 3.8 within the virtualenv? If the error keeps happening after upgrading setuptools and wheel I would recommend trying out the Docker method. Also consider joining our [community](https://community.deeplearning.ai/) where our mentors and team will help you. You can also find more information on our community in this Reading Item within [Coursera](https://www.coursera.org/learn/introduction-tensorflow/ungradedLti/3L0GK/important-have-questions-issues-or-ideas-join-our-community).



> @dzzzzdy are you using python 3.8 within the virtualenv? If the error keeps happening after upgrading setuptools and wheel I would recommend trying out the Docker method. Also consider joining our [community](https://community.deeplearning.ai/) where our mentors and team will help you. You can also find more information on our community in this Reading Item within [Coursera](https://www.coursera.org/learn/introduction-tensorflow/ungradedLti/3L0GK/important-have-questions-issues-or-ideas-join-our-community).

Thank you for your suggestions!
