### ISSUE TITLE
Course 3 | Week 2: TfidfVectorizer has no method get_feature_names()

### ISSUE THREAD

**Issue by weissmanuel** [https-deeplearning-ai/machine-learning-engineering-for-production-public#89]
In the ungraded lab of week 2 in course 3 (Ungraded lab: Algorithmic Dimensionality Reduction), the method `get_feature_names()` for `TfidfVectorizer` does not exists.

According to the sklearn documentation it need to be changed to `get_feature_names_out()`.
https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html

There are two occurrences with `vectorizer.get_feature_names()` in the notebook.

**Comment by Nnamaka** [comment]
I can confirm the error

as stated by @weissmanuel use `get_feature_names_out()` instead of `get_feature_names()` 
see [here](https://stackoverflow.com/questions/70215049/attributeerror-tfidfvectorizer-object-has-no-attribute-get-feature-names-out)
