### ISSUE TITLE
Typo error : C4_W2_Lab_1_FastAPI_Docker 

### ISSUE THREAD

**Issue by Nnamaka** [https-deeplearning-ai/machine-learning-engineering-for-production-public#94]
Hi guys, In an effort to contribute and show appreciation to this Great course and the community, I thought I should point it out.

.
![Screenshot (1030)](https://github.com/https-deeplearning-ai/machine-learning-engineering-for-production-public/assets/54998610/7f2038a8-4521-4599-bd3f-80620f871f52)

**Comment by cfav-dev** [comment]
Thank you Nnamaka!
