### ISSUE TITLE
C4_W2_Lab_1_FastAPI_Docker/with-batch/app/main.py conlist() argument error

### ISSUE THREAD

**Issue by noib** [https-deeplearning-ai/machine-learning-engineering-for-production-public#96]
"TypeError: conlist() got an unexpected keyword argument 'min_items'" when running the app

Current pydantic documentation shows argument should be 'min_length' instead of 'min_items' (and 'max_length' instead of 'max_items')
https://docs.pydantic.dev/latest/api/types/#pydantic.types.conlist

After changing the argument names in main.py, the app runs correctly

**Comment by cfav-dev** [comment]
Thank you! The command was updated a couple of weeks ago. Next time, you can also post feedback in our community platform for better visibility. There are instructions in Week 1 on how to join. Thanks again!

**Comment by cfav-dev** [comment]
Thank you! The command was updated a couple of weeks ago. Next time, you can also post feedback in our community platform for better visibility. There are instructions in Week 1 on how to join. Thanks again!
