### ISSUE TITLE
C3_W4_Model Remediation: a reference link is broken

### ISSUE THREAD

**Issue by elir0d** [https-deeplearning-ai/machine-learning-engineering-for-production-public#97]
- Item link: Not provide
- Specific issue area: Optional resources
- Description: One of the links provides to additional resources is broken with 404 error
- Proposed solution: Update or remove the link from the list provide.

**Comment by elir0d** [comment]
A learner report a issue with a broken link:
https://community.deeplearning.ai/t/link-broken/399178

**Comment by cfav-dev** [comment]
Thanks, elirod!

**Comment by elir0d** [comment]
you welcome
