### ISSUE TITLE
cannot convert float infinity to integer

### ISSUE THREAD

**Issue by SachinMishra-ux** [https-deeplearning-ai/machine-learning-engineering-for-production-public#98]
<img width="1047" alt="image" src="https://github.com/https-deeplearning-ai/machine-learning-engineering-for-production-public/assets/63257356/ea77b749-79ba-47c2-bcd9-4a305ee6cfec">

This image after after converting it into numpy having some infinite float value resulting in cannot convert float infinity to integer

**Comment by cfav-dev** [comment]
Hi Sachin. Sorry for the late reply. Next time, you can post or search for topics in our community. There might be mentors/learners there who have the same setup and can help you. If you haven't joined yet, you can find instructions in Week 1 of your classroom. Thanks!
